/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 ./public/assets_3D/Mungyeong_South_Korea.glb -i 
Files: ./public/assets_3D/Mungyeong_South_Korea.glb [2.2MB] > D:\Trabajos\Propio\REACT\reactThreeFiber\Mungyeong_South_Korea-transformed.glb [1.1MB] (50%)
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { RigidBody } from "@react-three/rapier";

export default function City(props) {
  const { nodes, materials } = useGLTF(
    "assets_3D/Mungyeong_South_Korea-transformed.glb"
  );
  return (
    <group {...props} dispose={null}>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh
          geometry={nodes.base.geometry}
          material={materials.map}
          position={[0, -0.005, 0]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.02, 0.02, 0.02]}
        />
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh
          geometry={nodes.highway_construction.geometry}
          material={nodes.highway_construction.material}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.02, 0.02, 0.02]}
        />
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh
          geometry={nodes.aeroway_he.geometry}
          material={materials.aeroway}
          position={[-86.317, 0, -22.851]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.02, 0.02, 0.02]}
        />
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh
          geometry={nodes.amenity_pa.geometry}
          material={materials.amenity}
          position={[-7.874, -0.003, 1.36]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.02, 0.02, 0.02]}
        />
      </RigidBody>
      <RigidBody type="fixed" colliders="trimesh">
        <mesh
          geometry={nodes.name____.geometry}
          material={materials.name}
          position={[-69.943, 0, -68.145]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.02, 0.02, 0.02]}
        />
      </RigidBody>
    </group>
  );
}

useGLTF.preload("assets_3D/Mungyeong_South_Korea-transformed.glb");
